### ISSUE TITLE
FSharp.Compatibility.Ocaml.Big_int.big_int_of_string does not parse hex and octal notation correctly.

### ISSUE THREAD

**Issue by A-Manning** [fsprojects/FSharp.Compatibility#18]
`FSharp.Compatibility.Ocaml.Big_int.big_int_of_string` does not parse hex and octal notation correctly.

Ocaml's `Z.of_string` can parse hex and octal notation, whereas F#'s cannot.

**Comment by A-Manning** [comment]
The following should all be true: 
`big_int_of_string "0xABC"   = bigint 2748`
`big_int_of_string "-0xABC"  = bigint (-2748)`
`big_int_of_string "0xabc"   = bigint 2748`
`big_int_of_string "0xaBc"   = bigint 2748`
`big_int_of_string "0o123"   = bigint 291`
`big_int_of_string "0b101"   = bigint 5`

**Comment by nikswamy** [comment]
Would be great to have a fix for this. Thanks!

**Comment by A-Manning** [comment]
@nikswamy  https://github.com/fsprojects/FSharp.Compatibility/pull/19
