### ISSUE TITLE
Too many dependencies!

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/FSharp.Compatibility#6]
When I bring FSharp.Compatibility.Ocaml in a get assembly references to `FSharp.Compatibility.OCaml`, `FSharp.PowerPack`, `FSharp.PowerPack.Linq`, `FSharp.PowerPack.MetaData`, `FSharp.PowerPack.Parallel.Seq`.

Thats a lot of dependencies just to use String.uncapitalize from Ocaml !!

**Comment by dsyme** [comment]
The dependencies were minimized in prior work and in #7 . However the nuget packages need to be updated.
